import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { useSearchParams } from 'react-router'
import { Empty, ErrorBanner, Field, FilterBar, Loading, Missing } from '@/components/hub/common'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { get, qs } from '@/lib/api'
import { addDays, fmtDate, today } from '@/lib/format'
import { t, tv } from '@/lib/i18n'
import { CoordinationRegister, type RegisterContext } from './CoordinationRegister'
import { CommandForm, CoordStatus, FieldsCommand, PersonLabel, RegisterPager, SelectField, SourceLink, WorkLink, personName, peopleChoices, disciplineChoices, sourceChoices, workChoices, workRef, type RecordVersion, type SourceRevision, type SourceHead, type FormField, type InputUse } from './CoordinationForms'

type Notice = RecordVersion & { key: string; title: string; ownerId: string; projectDisciplineId: string; oldRevisionId: string; newRevisionId: string; description: string; scope: string; assessmentDueDate: string; effectiveDate: string; status: string }
type Assessment = RecordVersion & { targetType: string; targetId: string; ownerId: string; reviewerId?: string; inputUseId?: string; handoffId?: string; revisionUsedId: string; status: string; acknowledgedAt?: string; rationale?: string; evidenceUrl?: string; correctionTaskId?: string; effortImpactHours?: number; dateImpactDays?: number; retainOldRevision: boolean; retentionApprovedBy?: string; retentionReason?: string; verifiedBy?: string; verifiedAt?: string }
type Detail = { notice: Notice; assessments: Assessment[]; completeAssessmentIds: string[]; oldRevision: SourceRevision; newRevision: SourceRevision; head: SourceHead; actorId: string; canWrite: boolean; canPublish: boolean; canManage: boolean; uses: InputUse[] }
const reason: FormField = { name: 'reason', label: 'coord.reason', type: 'textarea' }
const subhead = 'text-base/6 font-semibold', check = 'mt-0.5 size-4 shrink-0 accent-(--primary)'
const dl = 'grid grid-cols-[minmax(8rem,auto)_1fr] gap-x-4 gap-y-2'
/** A warning that names what to do next, with its symbol (§13.0). */
const Warn = ({ children }: { children: string }) => <p role="status" className="flex gap-2 rounded-md border border-warn/40 bg-warn-bg px-3 py-2 text-warn"><span aria-hidden>▲</span><span>{children}</span></p>
export function ChangesTab() { return <CoordinationRegister kind="changes" statuses={['Draft', 'Open', 'Closed', 'Cancelled']} create={c => <SourceForm {...c} />} detail={c => <ChangeDetail {...c} />} extra={c => <InputRegister {...c} />} /> }
function SourceForm({ options: o, projectId, open, close, refresh }: RegisterContext & { close: () => void }) {
  const [mode, setMode] = useState('Deliverable'), [previous, setPrevious] = useState(''), [deliverable, setDeliverable] = useState('')
  const [v, set] = useState({ sourceSystem: 'Manual', externalIdentifier: '', title: '', revision: '', url: '', issuer: '', scope: '', sourceCheckedAt: '', ownerId: '', projectDisciplineId: '', description: '', effectiveDate: today(), assessmentDueDate: addDays(today(), 7) })
  const update = (key: string, value: string) => set(s => ({ ...s, [key]: value }))
  const prior = o.sources.find(s => s.revision.id === previous), work = o.deliverables.find(d => d.id === deliverable), head = o.heads.find(h => h.currentRevisionId === previous)
  function choosePrevious(id: string) { setPrevious(id); const s = o.sources.find(s => s.revision.id === id)?.revision, h = o.heads.find(h => h.currentRevisionId === id); if (s) { setMode(s.deliverableId ? 'Deliverable' : 'External'); setDeliverable(s.deliverableId ?? ''); set(v => ({ ...v, sourceSystem: s.sourceSystem || (s.deliverableId ? 'Deliverable' : 'Manual'), externalIdentifier: s.externalIdentifier || s.sourceKey, title: s.title, issuer: s.issuer, scope: s.scope, ownerId: h?.ownerId ?? '', projectDisciplineId: h?.projectDisciplineId ?? '' })) } }
  function chooseDeliverable(id: string) { setDeliverable(id); const w = o.deliverables.find(d => d.id === id); if (w) set(v => ({ ...v, sourceSystem: 'Deliverable', externalIdentifier: w.key, title: w.name, revision: w.revision ?? '', url: w.transmittalUrl ?? '', ownerId: w.ownerId ?? '', projectDisciplineId: w.projectDisciplineId, scope: w.name })) }
  return <CommandForm title={t('changes.new')} hint={t('change.registerHint')} path={`projects/${projectId}/source-revisions`} payload={() => ({ ...v, sourceCheckedAt: v.sourceCheckedAt ? new Date(v.sourceCheckedAt).toISOString() : null, deliverableId: mode === 'Deliverable' ? deliverable : null, deliverableRowVersion: work?.rowVersion, supersedesId: previous || null, headRowVersion: head?.rowVersion, description: previous ? v.description : null, effectiveDate: previous ? v.effectiveDate : null, assessmentDueDate: previous ? v.assessmentDueDate : null })} onClose={close} onDone={id => { refresh(); close(); if (previous) open(id) }}>
    <SelectField label={t('change.supersedes')} value={previous} onChange={choosePrevious} required={false} choices={sourceChoices(o)} />
    {!prior && <div className="grid gap-3 sm:grid-cols-2"><SelectField label={t('change.sourceType')} value={mode} onChange={setMode} choices={[{ value: 'Deliverable', label: t('handoff.deliverables') }, { value: 'External', label: t('change.external') }]} />{mode === 'Deliverable' && <SelectField label={t('handoff.source')} value={deliverable} onChange={chooseDeliverable} choices={o.deliverables.filter(d => d.ownerId === o.actorId || o.manageDisciplineIds.includes(d.projectDisciplineId)).map(d => ({ value: d.id, label: `${d.key} · ${d.name}` }))} />}</div>}
    {prior && <p className="rounded-md bg-muted px-4 py-3 text-sm"><SourceLink source={prior.revision} /> → {t('change.replacement')}</p>}
    <div className="grid gap-3 sm:grid-cols-2"><SelectField label={t('coord.owner')} value={v.ownerId} onChange={val => update('ownerId', val)} choices={peopleChoices(o)} /><SelectField label={t('coord.discipline')} value={v.projectDisciplineId} onChange={val => update('projectDisciplineId', val)} choices={disciplineChoices(o)} /></div>
    <div className="grid gap-3 sm:grid-cols-2">{(['sourceSystem', 'externalIdentifier', 'title', 'revision', 'url', 'issuer', 'sourceCheckedAt'] as const).map(key => <Field key={key} label={t(`change.${key}`)} htmlFor={`source-${key}`} optional={key === 'sourceCheckedAt'}><Input id={`source-${key}`} required={key !== 'sourceCheckedAt'} readOnly={!!prior && ['sourceSystem', 'externalIdentifier'].includes(key)} type={key === 'url' ? 'url' : key === 'sourceCheckedAt' ? 'datetime-local' : 'text'} value={v[key]} onChange={e => update(key, e.target.value)} /></Field>)}</div>
    <Field label={t('change.scope')} htmlFor="source-scope"><Textarea id="source-scope" required maxLength={2000} value={v.scope} onChange={e => update('scope', e.target.value)} /></Field>
    {previous && <><Field label={t('change.description')} htmlFor="source-description"><Textarea id="source-description" required maxLength={4000} value={v.description} onChange={e => update('description', e.target.value)} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label={t('change.effective')} htmlFor="source-effective"><Input id="source-effective" required type="date" value={v.effectiveDate} onChange={e => update('effectiveDate', e.target.value)} /></Field><Field label={t('change.due')} htmlFor="source-due"><Input id="source-due" required type="date" value={v.assessmentDueDate} onChange={e => update('assessmentDueDate', e.target.value)} /></Field></div><p className="text-sm text-muted-foreground">{t('change.draftHint')}</p></>}
  </CommandForm>
}
function InputRegister(c: RegisterContext) {
  const { options: o, projectId } = c, [sp, setSp] = useSearchParams(), [adopting, setAdopting] = useState(false)
  const target = sp.get('target') ?? '', [type, id] = target.split(':'), page = Math.max(1, Number(sp.get('inputsPage')) || 1)
  const q = useQuery({ queryKey: ['input-uses', projectId, target, page], queryFn: () => get<{ items: InputUse[]; totalCount: number; pageSize: number; assessments: { targetId: string; changeNoticeId: string; key: string; newRevisionId: string; status: string; noticeStatus: string }[]; history: { id: string; inputUseId: string; sourceRevisionId: string; reason: string; createdAt: string; createdBy: string }[] }>(`projects/${projectId}/input-uses${qs({ targetType: type, targetId: id, page })}`) })
  const change = (key: string, value: string) => { const next = new URLSearchParams(sp); if (value) next.set(key, value); else next.delete(key); if (key === 'target') next.delete('inputsPage'); setSp(next) }
  return <section aria-labelledby="change-inputs-h" className="space-y-4 border-t pt-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="max-w-3xl"><h2 id="change-inputs-h" className="text-lg/[26px] font-semibold tracking-[-0.2px]">{t('change.inputs')}</h2><p className="mt-1 text-base/6 text-muted-foreground">{t('change.detectionBoundary')}</p></div>{o.canWrite && <Button variant="outline" onClick={() => setAdopting(true)}>{t('change.recordUse')}</Button>}</div>
    <FilterBar><div className="w-full sm:max-w-md"><SelectField label={t('change.target')} value={target} onChange={v => change('target', v)} required={false} choices={workChoices(o)} /></div></FilterBar>
    {q.isPending ? <div className="rounded-lg border bg-card"><Loading rows={2} /></div> : q.error ? <ErrorBanner error={q.error} retry={() => q.refetch()} /> : <>
      {!q.data.items.length && <div className="rounded-lg border bg-card"><Empty>{t('change.noInputs')}</Empty></div>}
      <div className="grid gap-3 xl:grid-cols-2">{q.data.items.map(u => { const used = o.sources.find(s => s.revision.id === u.sourceRevisionId)?.revision, head = o.heads.find(h => h.identity === u.sourceIdentity), current = o.sources.find(s => s.revision.id === head?.currentRevisionId)?.revision; return <article key={u.id} className="space-y-3 rounded-lg border bg-card p-5 text-sm">
        <h3 className="font-semibold"><WorkLink options={o} type={u.targetType} id={u.targetId} number={c.number} /></h3>
        <dl className={dl}>
          <dt className="text-muted-foreground">{t('change.revisionUsed')}</dt><dd>{used ? <SourceLink source={used} /> : <Missing />}</dd>
          <dt className="text-muted-foreground">{t('change.current')}</dt><dd>{current ? <SourceLink source={current} /> : <span className="text-muted-foreground">{t('coord.unavailable')}</span>}</dd>
        </dl>
        {current?.id !== used?.id && <Warn>{t('change.olderUsed')}</Warn>}
        <p className="whitespace-pre-wrap">{u.intendedUse}</p>
        {q.data.assessments.filter(a => a.targetId === u.targetId && a.newRevisionId === current?.id).map(a => <p key={a.changeNoticeId}>{t('change.assessment')}: <button className="text-left text-primary underline underline-offset-4" onClick={() => c.open(a.changeNoticeId)}>{a.key} · {tv(a.status)} · {tv(a.noticeStatus)}</button></p>)}
        <p className="text-xs/[18px] text-muted-foreground">{t('change.adopted')}: <span className="tabular-nums">{new Date(u.adoptedAt).toLocaleString()}</span> · {personName(o, u.adoptedBy)}</p>
        {used && <p className="text-xs/[18px] text-muted-foreground">{t('change.registered')}: <span className="tabular-nums">{new Date(used.createdAt).toLocaleString()}</span> · {t('change.sourceCheckedAt')}: {used.sourceCheckedAt ? new Date(used.sourceCheckedAt).toLocaleString() : t('change.notChecked')}</p>}
        <details className="border-t pt-2"><summary className="cursor-pointer py-1 font-medium">{t('coord.history')}</summary>{q.data.history.filter(h => h.inputUseId === u.id).map(h => <p className="mt-2" key={h.id}>{o.sources.find(s => s.revision.id === h.sourceRevisionId)?.revision.revision} · {new Date(h.createdAt).toLocaleString()} · {h.reason}</p>)}</details>
      </article> })}</div>
      <RegisterPager label={t('change.inputsPager')} page={page} total={q.data.totalCount} pageSize={q.data.pageSize} onPage={n => change('inputsPage', String(n))} />
    </>}
    <details className="rounded-lg border bg-card px-5 py-3"><summary className="cursor-pointer py-1 text-sm font-semibold">{t('change.sources')}</summary><p className="my-2 text-xs/[18px] text-muted-foreground">{t('handoff.manualRevision')}</p>{o.sources.map(s => <div key={s.revision.id} className="space-y-1 border-t py-2 text-sm"><SourceLink source={s.revision} /><p className="text-muted-foreground"><span className={s.isCurrent ? 'font-medium text-foreground' : undefined}>{s.isCurrent ? t('change.current') : s.published ? t('change.historical') : t('change.unpublished')}</span> · {s.revision.issuer} · <span className="tabular-nums">{new Date(s.revision.createdAt).toLocaleString()}</span></p></div>)}</details>
    {adopting && <AdoptForm {...c} initialTarget={target} close={() => setAdopting(false)} uses={q.data?.items ?? []} />}
  </section>
}
function AdoptForm({ options: o, projectId, refresh, close, initialTarget, uses }: RegisterContext & { close: () => void; initialTarget: string; uses: InputUse[] }) {
  const [target, setTarget] = useState(initialTarget), [source, setSource] = useState(''), [purpose, setPurpose] = useState(''), [reason, setReason] = useState('')
  const [type, id] = target.split(':'), work = workRef(o, type, id), registered = o.sources.find(s => s.revision.id === source), use = uses.find(u => u.targetId === id && u.sourceIdentity === registered?.identity)
  // Query the selected work independently: its existing input may be outside the visible page.
  const q = useQuery({ queryKey: ['input-uses', projectId, target, 'adopt'], queryFn: () => get<{ items: InputUse[] }>(`projects/${projectId}/input-uses${qs({ targetType: type, targetId: id })}`), enabled: !!id })
  return <CommandForm title={t('change.recordUse')} hint={t('change.adoptHint')} path={`projects/${projectId}/input-uses`} payload={() => ({ targetType: type, targetId: id, targetRowVersion: work?.rowVersion, sourceRevisionId: source, expectedCurrentRevisionId: source, inputUseRowVersion: (q.data?.items.find(u => u.sourceIdentity === registered?.identity) ?? use)?.rowVersion, intendedUse: purpose, reason })} onClose={close} onDone={() => { refresh(); close() }}>
    <SelectField label={t('change.target')} value={target} onChange={setTarget} choices={workChoices(o).filter(c => { const [type, id] = c.value.split(':'); return workRef(o, type, id)?.ownerId === o.actorId })} /><SelectField label={t('change.current')} value={source} onChange={setSource} choices={sourceChoices(o)} />
    <Field label={t('handoff.purpose')} htmlFor="input-purpose"><Textarea id="input-purpose" required value={purpose} onChange={e => setPurpose(e.target.value)} /></Field><Field label={t('coord.reason')} htmlFor="input-reason"><Textarea id="input-reason" required value={reason} onChange={e => setReason(e.target.value)} /></Field>{q.error && <ErrorBanner error={q.error} />}
  </CommandForm>
}
function ChangeDetail(c: RegisterContext & { id: string; close: () => void }) {
  const { options: o, projectId, id, close } = c
  const q = useQuery({ queryKey: ['change-detail', projectId, id], queryFn: () => get<Detail>(`projects/${projectId}/changes/${id}`) })
  const [action, setAction] = useState<{ type: string; assessment?: Assessment } | null>(null), d = q.data, n = d?.notice
  const done = () => { setAction(null); c.refresh(); q.refetch() }
  return <><Dialog open onOpenChange={v => !v && close()}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-4xl"><DialogHeader><DialogTitle>{n ? `${n.key} · ${n.title}` : t('changes.title')}</DialogTitle><DialogDescription>{t('change.detectionBoundary')}</DialogDescription></DialogHeader>
    {q.isPending ? <Loading rows={4} /> : q.error ? <ErrorBanner error={q.error} retry={() => q.refetch()} /> : d && n && <div className="space-y-6 text-sm">
      <div className="flex flex-wrap items-center gap-2"><CoordStatus status={n.status} /><span className="flex-1" />{d.canWrite && <>{n.status === 'Draft' && d.canPublish && <Button size="sm" onClick={() => setAction({ type: 'publish' })}>{t('change.publish')}</Button>}{n.status === 'Open' && n.ownerId === d.actorId && <Button size="sm" onClick={() => setAction({ type: 'close' })}>{t('change.close')}</Button>}{['Draft', 'Open'].includes(n.status) && d.canManage && <><Button size="sm" variant="outline" onClick={() => setAction({ type: 'noticeAssign' })}>{t('change.assignNotice')}</Button><Button size="sm" variant="ghost" className="text-bad hover:text-bad" onClick={() => setAction({ type: 'cancel' })}>{t('change.cancel')}</Button></>}</>}</div>
      <dl className={dl}>
        <dt className="text-muted-foreground">{t('coord.owner')}</dt><dd><PersonLabel options={o} id={n.ownerId} /></dd>
        <dt className="text-muted-foreground">{t('change.effective')}</dt><dd className="tabular-nums">{fmtDate(n.effectiveDate)}</dd>
        <dt className="text-muted-foreground">{t('change.due')}</dt><dd className="tabular-nums">{fmtDate(n.assessmentDueDate)}</dd>
        <dt className="text-muted-foreground">{t('change.scope')}</dt><dd className="whitespace-pre-wrap">{n.scope}</dd>
      </dl>
      <p className="whitespace-pre-wrap text-base/6">{n.description}</p>
      <div className="space-y-2"><div className="grid gap-3 sm:grid-cols-2">{[d.oldRevision, d.newRevision].map((s, i) => <section key={s.id} className="space-y-1 rounded-lg border bg-muted p-4"><h3 className="mb-2 font-semibold">{t(i ? 'change.proposed' : 'change.previous')}</h3><SourceLink source={s} /><p>{s.issuer}</p><p className="text-muted-foreground">{t('change.registered')}: <span className="tabular-nums">{new Date(s.createdAt).toLocaleString()}</span></p><p className="text-muted-foreground">{t('change.sourceCheckedAt')}: {s.sourceCheckedAt ? new Date(s.sourceCheckedAt).toLocaleString() : t('change.notChecked')}</p></section>)}</div><p className="text-xs/[18px] text-muted-foreground">{t('handoff.manualRevision')}</p></div>
      <section className="space-y-3"><h3 className={subhead}>{t('change.assessments')}</h3>{!d.assessments.length && <p className="text-muted-foreground">{t(n.status === 'Draft' ? 'change.publishHint' : 'change.noAssessments')}</p>}{d.assessments.map(a => {
        const w = workRef(o, a.targetType, a.targetId), canManage = !!w && o.manageDisciplineIds.includes(w.projectDisciplineId), owner = a.ownerId === d.actorId && a.ownerId === w?.ownerId, live = d.canWrite && n.status === 'Open', used = d.uses.find(u => u.id === a.inputUseId)?.sourceRevisionId ?? a.revisionUsedId, current = o.sources.find(s => s.revision.id === d.head.currentRevisionId)?.revision, complete = d.completeAssessmentIds.includes(a.id)
        return <article key={a.id} className="space-y-3 rounded-lg border p-4">
          <h4 className="font-semibold"><WorkLink options={o} type={a.targetType} id={a.targetId} number={c.number} /></h4>
          <dl className={dl}>
            <dt className="text-muted-foreground">{t('coord.owner')}</dt><dd><PersonLabel options={o} id={a.ownerId} /></dd>
            <dt className="text-muted-foreground">{t('review.verifier')}</dt><dd><PersonLabel options={o} id={a.reviewerId} /></dd>
            <dt className="text-muted-foreground">{t('change.current')}</dt><dd>{current?.revision ?? <Missing />}</dd>
            <dt className="text-muted-foreground">{t('change.revisionUsed')}</dt><dd>{o.sources.find(s => s.revision.id === used)?.revision.revision ?? <Missing />}</dd>
            <dt className="text-muted-foreground">{t('change.assessment')}</dt><dd><CoordStatus status={a.status} /></dd>
          </dl>
          {complete && <p className="flex items-center gap-1.5 font-medium text-done"><span aria-hidden>✓</span><span>{t('change.assessmentComplete')}</span></p>}{a.acknowledgedAt && <p className="text-xs/[18px] text-muted-foreground">{t('change.acknowledged')}: <span className="tabular-nums">{new Date(a.acknowledgedAt).toLocaleString()}</span></p>}{a.ownerId !== w?.ownerId && <Warn>{t('change.ownerChanged')}</Warn>}{a.rationale && <p className="whitespace-pre-wrap">{a.rationale}</p>}{a.evidenceUrl && <a className="text-primary underline underline-offset-4" href={a.evidenceUrl} target="_blank" rel="noopener noreferrer">{t('coord.evidence')}</a>}
          {a.correctionTaskId && <p>{t('change.correction')}: <WorkLink options={o} type="Task" id={a.correctionTaskId} number={c.number} /> · {t('change.effort')}: <span className="tabular-nums">{a.effortImpactHours}</span> · {t('change.dateImpact')}: <span className="tabular-nums">{a.dateImpactDays}</span></p>}{a.retainOldRevision && <p>{t(a.retentionApprovedBy ? 'change.retentionApproved' : 'change.retentionNeeded')}{a.retentionReason && ` · ${a.retentionReason}`}</p>}{a.verifiedBy && <p>{t('change.verified')}: {personName(o, a.verifiedBy)} · {a.verifiedAt && new Date(a.verifiedAt).toLocaleString()}</p>}
          {live && <div className="flex flex-wrap gap-2 border-t pt-3">{owner && <>{!a.acknowledgedAt && <Button size="sm" variant="outline" onClick={() => setAction({ type: 'acknowledge', assessment: a })}>{t('change.acknowledge')}</Button>}<Button size="sm" onClick={() => setAction({ type: 'disposition', assessment: a })}>{t('change.disposition')}</Button>{['Unaffected', 'Update Required'].includes(a.status) && a.retainOldRevision && <Button size="sm" variant="outline" onClick={() => setAction({ type: 'adopt', assessment: a })}>{t('change.adopt')}</Button>}</>}{canManage && <><Button size="sm" variant="outline" onClick={() => setAction({ type: 'assign', assessment: a })}>{t('change.assign')}</Button>{a.retainOldRevision && !a.retentionApprovedBy && ['Unaffected', 'Update Required'].includes(a.status) && <Button size="sm" variant="outline" onClick={() => setAction({ type: 'approveRetention', assessment: a })}>{t('change.approveRetention')}</Button>}</>}{a.reviewerId === d.actorId && a.status === 'Update Required' && <Button size="sm" onClick={() => setAction({ type: 'resolve', assessment: a })}>{t('change.resolve')}</Button>}</div>}
        </article>
      })}</section>
    </div>}
  </DialogContent></Dialog>{action && d && <ChangeCommand c={c} d={d} action={action} close={() => setAction(null)} done={done} />}</>
}
function ChangeCommand({ c, d, action, close, done }: { c: RegisterContext; d: Detail; action: { type: string; assessment?: Assessment }; close: () => void; done: () => void }) {
  const o = c.options, n = d.notice, a = action.assessment, type = action.type, base = `projects/${c.projectId}/changes/${n.id}`
  const [extra, setExtra] = useState<string[]>([]), [status, setStatus] = useState(a?.status === 'Pending Assessment' ? 'Unaffected' : a?.status ?? 'Unaffected')
  if (type === 'publish') return <CommandForm path={`${base}/publish`} title={t('change.publish')} hint={t('change.publishHint')} payload={() => ({ rowVersion: n.rowVersion, headRowVersion: d.head.rowVersion, additionalTargets: extra.map(key => { const [type, id] = key.split(':'); return { targetType: type, targetId: id, rowVersion: workRef(o, type, id)?.rowVersion } }) })} onClose={close} onDone={done}><fieldset className="space-y-1 rounded-lg border p-4"><legend className="px-1 text-sm font-semibold">{t('change.additional')}</legend>{workChoices(o).map(w => <label className="flex items-start gap-2 py-1 text-sm" key={w.value}><input type="checkbox" className={check} checked={extra.includes(w.value)} onChange={e => setExtra(v => e.target.checked ? [...v, w.value] : v.filter(x => x !== w.value))} />{w.label}</label>)}</fieldset><p className="text-sm text-muted-foreground">{t('change.detectionBoundary')}</p></CommandForm>
  let fields: FormField[] = [reason], initial: Record<string, string> = {}, path = `${base}/action`, build: (v: Record<string, string>) => object = v => ({ ...v, rowVersion: n.rowVersion, action: type === 'noticeAssign' ? 'assign' : type })
  if (type === 'noticeAssign') fields.unshift({ name: 'ownerId', label: 'coord.owner', choices: peopleChoices(o) })
  if (a) {
    path = `${base}/assessments/${a.id}`
    const w = workRef(o, a.targetType, a.targetId), use = d.uses.find(u => u.id === a.inputUseId)
    fields = type === 'acknowledge' ? [] : [{ name: 'rationale', label: 'coord.rationale', type: 'textarea' }]
    if (type === 'assign') fields.unshift({ name: 'reviewerId', label: 'review.verifier', choices: peopleChoices(o) })
    if (type === 'disposition') { fields = [{ name: 'rationale', label: 'coord.rationale', type: 'textarea' }, { name: 'evidenceUrl', label: 'coord.evidenceUrl', type: 'url' }]; initial = { rationale: a.rationale ?? '', evidenceUrl: a.evidenceUrl ?? '' }; if (status === 'Update Required') fields.push({ name: 'correctionTaskId', label: 'change.correction', choices: o.tasks.map(w => ({ value: w.id, label: `${w.key} · ${w.name}` })) }, { name: 'effortImpactHours', label: 'change.effort', type: 'number', min: 0 }, { name: 'dateImpactDays', label: 'change.dateImpact', type: 'number' }) }
    build = v => ({ ...v, rowVersion: a.rowVersion, action: type, status: type === 'disposition' ? status : undefined, ownerId: type === 'assign' ? w?.ownerId : undefined, targetRowVersion: w?.rowVersion, inputUseRowVersion: use?.rowVersion, expectedCurrentRevisionId: d.head.currentRevisionId, correctionTaskRowVersion: o.tasks.find(t => t.id === (v.correctionTaskId ?? a.correctionTaskId))?.rowVersion, effortImpactHours: v.effortImpactHours != null ? Number(v.effortImpactHours) : undefined, dateImpactDays: v.dateImpactDays != null ? Number(v.dateImpactDays) : undefined })
  }
  if (type === 'disposition') return <DispositionForm title={t('change.disposition')} path={path} fields={fields} initial={initial} build={build} status={status} setStatus={setStatus} close={close} done={done} />
  return <FieldsCommand title={t(`change.command.${type}`)} path={path} fields={fields} initial={initial} build={build} onClose={close} onDone={done} hint={type === 'acknowledge' ? t('change.ackHint') : undefined} />
}
function DispositionForm({ title, path, fields, initial, build, status, setStatus, close, done }: { title: string; path: string; fields: FormField[]; initial: Record<string, string>; build: (v: Record<string, string>) => object; status: string; setStatus: (s: string) => void; close: () => void; done: () => void }) {
  const [v, set] = useState(initial)
  return <CommandForm title={title} path={path} payload={() => build(v)} onClose={close} onDone={done} hint={t('change.dispositionHint')}><SelectField label={t('change.assessment')} value={status} onChange={setStatus} choices={['Unaffected', 'Update Required', 'Clarification Needed'].map(s => ({ value: s, label: tv(s) }))} />{fields.map(f => f.choices ? <SelectField key={f.name} label={t(f.label)} value={v[f.name] ?? ''} onChange={value => set(s => ({ ...s, [f.name]: value }))} choices={f.choices} /> : <Field key={f.name} label={t(f.label)} htmlFor={`assessment-${f.name}`}>{f.type === 'textarea' ? <Textarea id={`assessment-${f.name}`} required value={v[f.name] ?? ''} onChange={e => set(s => ({ ...s, [f.name]: e.target.value }))} /> : <Input id={`assessment-${f.name}`} required type={f.type} min={f.min} step={f.name === 'dateImpactDays' ? 1 : 'any'} value={v[f.name] ?? ''} onChange={e => set(s => ({ ...s, [f.name]: e.target.value }))} />}</Field>)}</CommandForm>
}
