import { Fragment, useEffect, useRef, useState } from 'react'
import { Link } from 'react-router'
import { ChevronDown, ChevronRight, Lock, Plus } from 'lucide-react'
import { Avatar } from '@/components/hub/people'
import { Chip } from '@/components/hub/pills'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { fmtDate, shortDate } from '@/lib/format'
import { t } from '@/lib/i18n'
import { cn } from '@/lib/utils'
import { ErrorBanner, Spinner } from '@/components/hub/common'
import { confidenceLabel, hoursLabel, indicatorLabel, sourceTone, type PlannerCell, type PlannerEntry, type PlannerGridData, type PlannerPerson, visibilityLabel } from './labels'

export function PlannerGrid({ data, editable, onQuickAdd, onCell, onEntry, onTimeAway }: { data: PlannerGridData; editable: boolean; onQuickAdd: (personId: string, week: string, text: string, idempotencyKey: string) => Promise<void>; onCell: (person: PlannerPerson, cell: PlannerCell) => void; onEntry: (entry: PlannerEntry) => void; onTimeAway?: (person: PlannerPerson) => void }) {
  const [open, setOpen] = useState<Set<string>>(new Set())
  const [quick, setQuick] = useState<{ personId: string; week: string } | null>(null)
  const [text, setText] = useState(''); const [saving, setSaving] = useState(false); const [saveError, setSaveError] = useState<unknown>(null)
  const quickKey = useRef<string | null>(null)
  const origin = useRef<string | null>(null)
  const cellRefs = useRef<Record<string, HTMLButtonElement | null>>({})
  useEffect(() => { if (!quick && origin.current) { const key = origin.current; requestAnimationFrame(() => cellRefs.current[key]?.focus()); origin.current = null } }, [quick])
  const groups = new Map<string, PlannerPerson[]>()
  for (const person of data.people) { const key = person.supervisorName ?? t('planner.noSupervisor'); groups.set(key, [...(groups.get(key) ?? []), person]) }
  const toggle = (id: string) => setOpen((old) => { const next = new Set(old); if (next.has(id)) next.delete(id); else next.add(id); return next })
  const submitQuick = async () => { if (!quick || !text.trim() || saving) return; setSaving(true); setSaveError(null); try { await onQuickAdd(quick.personId, quick.week, text.trim(), quickKey.current ?? (quickKey.current = crypto.randomUUID())); setText(''); setQuick(null); quickKey.current = null } catch (error) { setSaveError(error) } finally { setSaving(false) } }
  const move = (personIndex: number, weekIndex: number, dx: number, dy: number) => {
    const target = data.people[personIndex + dy]?.cells[weekIndex + dx]
    const person = data.people[personIndex + dy]
    if (target && person) cellRefs.current[`${person.id}:${target.week}`]?.focus()
  }
  return <div className="scroll-region max-h-[76dvh] overflow-auto rounded-lg border bg-card" role="region" aria-label={t('planner.grid')}>{saveError != null && <ErrorBanner error={saveError} retry={() => void submitQuick()} />}
    <table className="w-full min-w-max border-separate border-spacing-0 text-sm" role="grid" aria-label={t('planner.grid')}>
      <caption className="sr-only">{t('planner.gridCaption')}</caption>
      <thead><tr>
        <th scope="col" className="sticky left-0 top-0 z-30 w-60 min-w-60 border-b border-r bg-muted px-4 py-3 text-left font-medium">{t('planner.person')}</th>
        {data.weeks.map((week) => <th key={week} scope="col" className={cn('sticky top-0 z-20 min-w-36 border-b border-r px-3 py-3 text-left font-medium', week === data.currentWeek ? 'bg-accent' : 'bg-muted')}><span className="block text-xs/[18px]">{t('planner.weekOf')}</span><span className="font-semibold">{shortDate(week)}</span></th>)}
      </tr></thead>
      {[...groups.entries()].map(([group, people]) => <tbody key={group}>
        <tr><th scope="rowgroup" className="sticky left-0 z-10 border-b border-r bg-sidebar px-4 py-2 text-left text-xs/[18px] font-semibold text-muted-foreground">{group} · {people.length}</th><td colSpan={data.weeks.length} className="border-b bg-sidebar" /></tr>
        {people.map((person) => { const personIndex = data.people.indexOf(person); const isOpen = open.has(person.id); return <Fragment key={person.id}>
          <tr>
            <th scope="row" className="sticky left-0 z-10 border-b border-r bg-card px-4 py-3 text-left align-top"><div className="flex items-start gap-2"><button type="button" className="mt-0.5 rounded-md p-1 hover:bg-muted" aria-expanded={isOpen} aria-label={isOpen ? t('planner.collapsePerson') : t('planner.expandPerson')} onClick={() => toggle(person.id)}>{isOpen ? <ChevronDown className="size-4" /> : <ChevronRight className="size-4" />}</button><Avatar id={person.id} name={person.displayName} /><span className="min-w-0"><span className="block break-words font-semibold">{person.displayName}</span><span className="block text-xs/[18px] text-muted-foreground">{t('planner.capacityValue', { hours: hoursLabel(person.weeklyCapacity) })}</span>{person.indicators.map((x) => <Chip key={x} tone="warn">{indicatorLabel(x)}</Chip>)}</span></div></th>
            {person.cells.map((cell, weekIndex) => { const key = `${person.id}:${cell.week}`; const editing = quick?.personId === person.id && quick.week === cell.week; return <td key={cell.week} aria-colindex={weekIndex + 2} className={cn('border-b border-r p-2 align-top', cell.week === data.currentWeek && 'bg-accent/40')}>
              {editing ? <form onSubmit={(e) => { e.preventDefault(); void submitQuick() }} className="space-y-1"><Input autoFocus disabled={saving} value={text} onChange={(e) => { setText(e.target.value); quickKey.current = null }} onKeyDown={(e) => { if (e.key === 'Escape' && !saving) { setQuick(null); setText(''); quickKey.current = null } }} placeholder={t('planner.quickPlaceholder')} aria-label={t('planner.quickAdd')} /><span className="text-xs text-muted-foreground">{saving ? <><Spinner /> {t('common.saving')}</> : t('planner.quickHint')}</span></form> : <button type="button" ref={(el) => { cellRefs.current[key] = el }} tabIndex={weekIndex === 0 && personIndex === 0 ? 0 : -1} className="w-full rounded-md p-1 text-left outline-offset-2 hover:bg-muted focus-visible:outline-2 focus-visible:outline-ring" aria-label={t('planner.cellLabel', { person: person.displayName, week: fmtDate(cell.week), remaining: hoursLabel(cell.remaining), planned: hoursLabel(cell.confirmed + cell.expected + cell.possible), capacity: hoursLabel(cell.capacity) })} onClick={() => { if (editable && (person.canCreateSelfEntry || person.canCreateManagerEntry)) { origin.current = key; setQuick({ personId: person.id, week: cell.week }); setText(''); quickKey.current = null } else onCell(person, cell) }} onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); if (editable && (person.canCreateSelfEntry || person.canCreateManagerEntry)) { origin.current = key; setQuick({ personId: person.id, week: cell.week }); setText(''); quickKey.current = null } else onCell(person, cell) } else if (e.key === 'Escape') { e.preventDefault(); onCell(person, cell) } else if (e.key === 'Home') { e.preventDefault(); move(personIndex, 0, 0, 0) } else if (e.key === 'End') { e.preventDefault(); move(personIndex, person.cells.length - 1, 0, 0) } else if (e.key === 'ArrowRight') { e.preventDefault(); move(personIndex, weekIndex, 1, 0) } else if (e.key === 'ArrowLeft') { e.preventDefault(); move(personIndex, weekIndex, -1, 0) } else if (e.key === 'ArrowDown') { e.preventDefault(); move(personIndex, weekIndex, 0, 1) } else if (e.key === 'ArrowUp') { e.preventDefault(); move(personIndex, weekIndex, 0, -1) } }}>
                <span className={cn('block text-base/6 font-semibold tabular-nums', cell.remaining < 0 && 'text-bad')}>{hoursLabel(cell.remaining)}</span><span className="block text-xs text-muted-foreground tabular-nums">{hoursLabel(cell.confirmed + cell.expected + cell.possible)} / {hoursLabel(cell.capacity)}</span><div className="mt-1 flex h-2 overflow-hidden rounded-sm border bg-muted" aria-hidden><span className="bg-ok" style={{ width: `${Math.min(100, cell.confirmed / Math.max(cell.capacity, 1) * 100)}%` }} /><span className="bg-warn" style={{ width: `${Math.min(100, cell.expected / Math.max(cell.capacity, 1) * 100)}%` }} /><span className="bg-(--acc-stripe)" style={{ width: `${Math.min(100, cell.possible / Math.max(cell.capacity, 1) * 100)}%` }} /></div>{cell.timeAway > 0 && <span className="mt-1 block text-xs text-muted-foreground">{t('planner.timeAwayHours', { hours: hoursLabel(cell.timeAway) })}</span>}{cell.overPlanned && <Chip tone="warn">{t('planner.indicator.over')}</Chip>}{cell.underPlanned && <Chip tone="idle">{t('planner.indicator.under')}</Chip>}{cell.staleEntries > 0 && <Chip tone="warn">{t('planner.indicator.stale')}</Chip>}{editable && (person.canCreateSelfEntry || person.canCreateManagerEntry) && <Plus className="float-right mt-1 size-3.5 text-muted-foreground" aria-hidden />}
              </button>}
              <button type="button" className="mt-1 min-h-8 w-full rounded-md px-2 text-left text-xs text-muted-foreground underline-offset-4 hover:bg-muted hover:text-foreground hover:underline focus-visible:outline-2 focus-visible:outline-ring" aria-label={t('planner.contributionsFor', { person: person.displayName, week: fmtDate(cell.week) })} onClick={() => onCell(person, cell)}>{t('planner.seeContributions')}</button>
            </td> })}
          </tr>
          {isOpen && <tr><th scope="row" className="sticky left-0 z-10 border-b border-r bg-muted px-12 py-2 text-left text-xs font-medium">{t('planner.entries')}</th>{data.weeks.map((week, weekIndex) => { const weekEntries = person.entries.filter((e) => e.matchesFilter !== false && e.startWeek <= week && e.endWeek >= week); return <td key={week} className="border-b border-r bg-muted/60 p-2 align-top"><div className="space-y-2">{weekEntries.map((entry) => <button type="button" key={`${entry.id}:${week}`} className={cn('flex w-full items-start gap-2 rounded-md border border-l-4 bg-card px-2 py-2 text-left text-sm hover:bg-accent focus-visible:outline-2 focus-visible:outline-ring', 'border-l-(--acc-stripe)', entry.visibility === 'Draft' && 'planner-draft', entry.confidence === 'Possible' && 'border-dotted')} data-accent={sourceTone(entry.sourceCategory)} onClick={() => onEntry(entry)}><span className="min-w-0 flex-1"><span className="block truncate">{entry.label}</span><span className="block text-xs text-muted-foreground">{confidenceLabel(entry.confidence)} · {visibilityLabel(entry.visibility, entry.ownerKind === 'Self')}</span></span><span className="shrink-0 tabular-nums">{hoursLabel(entry.hoursPerWeek)}</span>{entry.visibility === 'Draft' && <Lock className="mt-0.5 size-3.5 shrink-0" aria-label={t('planner.visibility.privateDraft')} />}</button>)}{weekEntries.length === 0 && <span className="block min-h-8 border border-dashed border-border/70 px-2 py-2 text-xs text-muted-foreground">{t('planner.noEntriesForWeek')}</span>}{person.approvedAllocations.flatMap((allocation) => allocation.weeks.filter((x) => x.week === week).map((x) => <div key={`${allocation.allocationId}:${week}`} className="flex items-center gap-2 rounded-md border bg-card px-2 py-2 text-xs"><span className="min-w-0 flex-1 truncate">{allocation.canOpen && allocation.projectId ? <Link className="underline-offset-4 hover:underline" to={`/projects/${allocation.projectId}/allocations?allocation=${allocation.allocationId}`}>{allocation.projectNumber} {allocation.projectName}</Link> : <span>{allocation.projectNumber} {allocation.projectName}</span>}</span><span className="tabular-nums">{hoursLabel(x.hours)} · {t('planner.approval.confirmed')}</span></div>))}{person.cells.find((c) => c.week === week)?.timeAway ? <div className="rounded-md border border-dashed bg-card px-2 py-2 text-xs text-muted-foreground">{t('planner.timeAwayHours', { hours: hoursLabel(person.cells.find((c) => c.week === week)?.timeAway ?? 0) })}</div> : null}{editable && weekIndex === 0 && person.canRecordTimeAway && onTimeAway && <Button size="sm" variant="outline" onClick={() => onTimeAway(person)}>{t('planner.recordTimeAway')}</Button>}</div></td> })}</tr>}
        </Fragment> })}
      </tbody>)}
      <tfoot><tr><th scope="row" className="sticky left-0 z-10 border-t border-r bg-muted px-4 py-3 text-left font-semibold">{t('planner.teamTotal')}</th>{data.weeks.map((week) => { const cells = data.people.map((p) => p.cells.find((c) => c.week === week)).filter(Boolean) as PlannerCell[]; return <td key={week} className="border-t border-r bg-muted px-3 py-3 text-sm tabular-nums">{hoursLabel(cells.reduce((n, c) => n + c.confirmed + c.expected, 0))}<span className="block text-xs text-muted-foreground">{cells.filter((c) => c.overPlanned).length} {t('planner.overPlannedPeople')}</span></td> })}</tr></tfoot>
    </table>
  </div>
}
