using System.Globalization;

namespace Hub.Api;

/// Server-side interface text (errors, notifications, emails) kept apart from code so a second
/// language can be added by translating this table (§22, Q7).
public static class Text
{
    static readonly Dictionary<string, string> En = new()
    {
        ["coord.stale"] = "This record changed. Refresh and review it before trying again.",
        ["coord.person"] = "Choose an active project participant who can perform this action.",
        ["coord.reference"] = "The referenced work or discipline is unavailable or outside this project.",
        ["coord.separation"] = "Choose a removal owner distinct from the affected work owner.",
        ["coord.transition"] = "This record cannot take that step from its current state.",
        ["submission.empty_manifest"] = "Add at least one deliverable revision to the submission manifest.",
        ["submission.empty_checks"] = "The submission checklist has not been created.",
        ["submission.coordinator_inactive"] = "The submission coordinator is no longer an active project participant.",
        ["submission.check_owner_inactive"] = "A checklist owner is no longer an active project participant.",
        ["submission.check_pending"] = "A required checklist item still needs evidence and a Pass decision.",
        ["submission.invalid_waiver"] = "This Not Applicable decision needs an optional check, a PM approver, a reason and evidence.",
        ["submission.deliverable_missing"] = "A required deliverable is unavailable, cancelled or deleted.",
        ["submission.revision_missing"] = "A manifest revision is unavailable or does not belong to its deliverable.",
        ["submission.revision_changed"] = "A manifest revision is no longer the current source revision.",
        ["submission.source_link_invalid"] = "A manifest source link is missing or invalid.",
        ["submission.review_not_current"] = "The required independent review is not approved for this round.",
        ["submission.review_round_not_approved"] = "The linked review round is not approved.",
        ["submission.review_manifest_mismatch"] = "The required review does not cover this exact deliverable revision.",
        ["submission.blocking_finding"] = "A blocking review finding still needs verified closure.",
        ["submission.handoff_pending"] = "A required handoff has not been accepted.",
        ["submission.change_pending"] = "An affected change assessment has not been resolved with evidence.",
        ["submission.input_changed"] = "An adopted design input is no longer the current revision.",
        ["submission.derived_check"] = "This required check is derived from its source record and cannot be manually waived.",
        ["submission.blocked"] = "Resolve every required readiness blocker before issuing this submission.",
        ["review.independent"] = "Choose an independent reviewer who has not authored or owned this work.",
        ["review.frozen"] = "This review cannot take that action in its current state.",
        ["review.source_unpublished"] = "Publish the source revision before reviewing it.",
        ["review.source_changed"] = "A newer source revision exists. Start a new round with the current revision.",
        ["review.manifest"] = "Choose one current revision per deliverable, from 1 to 200 deliverables.",
        ["review.assignments"] = "Assign one reviewer per required discipline, from 1 to 50 disciplines.",
        ["review.notification"] = "{0}: {1} — {2}",
        ["review.issued"] = "Reopen the issued or accepted deliverable before changing its required review or adopted inputs.",
        ["review.other_gate"] = "This deliverable already requires another review package.",
        ["review.start_first"] = "Start the review round first.",
        ["review.named_reviewer"] = "Only a named reviewer can perform this review action.",
        ["review.finding_transition"] = "This finding cannot take that step from its current state.",
        ["review.gate"] = "The required multidisciplinary review must be approved before this deliverable can be made ready or issued.",
        ["review.gate_revision"] = "The revision and any supplied source link must match the approved review manifest.",
        ["change.notification"] = "{0}: {1} — {2}",
        ["change.same_source"] = "Choose a revision of the same source.",
        ["change.current"] = "The current revision changed. Refresh and confirm the intended revision.",
        ["change.explicit_supersedes"] = "Select the current revision this revision supersedes.",
        ["change.future_check"] = "The source check time cannot be in the future.",
        ["change.duplicate_revision"] = "This exact source revision is already registered.",
        ["change.draft"] = "Only a draft change notice can be published.",
        ["change.targets"] = "Choose no more than 200 additional affected work items.",
        ["change.retain_via_assessment"] = "Retaining an older revision requires an impact assessment and PM or discipline lead approval.",
        ["change.adopt_via_assessment"] = "Record adoption through the open change assessment for this work.",
        ["change.frozen"] = "This change notice is closed or cancelled.",
        ["change.open"] = "Publish the change before recording assessments.",
        ["change.incomplete"] = "Every linked assessment needs an evidenced disposition, approved retention or adoption, and verified correction where required.",
        ["change.work_owner"] = "The assessment owner must be the current accountable owner of the affected work.",
        ["change.retention"] = "Retaining the older revision requires a PM or responsible discipline lead to approve a reason.",
        ["change.update_required"] = "Only an assessment requiring an update can be verified.",
        ["change.correction"] = "The linked correction task must be complete and independently verified with evidence.",
        ["change.assess_first"] = "Record an unaffected or update-required disposition before adopting the revision.",
        ["change.owner_changed"] = "The work owner changed. Ask a PM or responsible discipline lead to reassign the assessment.",
        ["change.estimate"] = "Enter an effort estimate of zero or more hours and a date impact in days.",
        ["change.correction_owner"] = "The correction task must belong to the accountable owner of the affected work.",
        ["issue.location_invalid"] = "Enter a valid location with the required alignment, station or coordinate details.",
        ["issue.stationRangeInvalid"] = "The station range must end at or after it starts.",
        ["issue.document_invalid"] = "Enter a document type, identifier, revision and source link.",
        ["issue.verifier_independent"] = "The issue owner cannot verify their own resolution.",
        ["issue.verifier_must_submit"] = "Only the named verifier can record this verification decision.",
        ["issue.verifier_not_appointed"] = "The current appointed verifier must record this decision.",
        ["issue.verification_required"] = "A current independent verification with evidence is required before resolution.",
        ["issue.document_unavailable"] = "An unavailable document reference cannot support resolution.",
        ["issue.coordination_reference_required"] = "A Coordination issue needs at least one location or drawing/model reference.",
        ["issue.type_closed"] = "The issue type can change only while the issue is Open or In Progress.",
        ["issue.type_has_verification"] = "This issue has verification records, so it must stay a Coordination issue.",
        ["param.issueType"] = "Issue type",
        ["export.reviews"] = "{0} — Multidisciplinary reviews",
        ["export.changes"] = "{0} — Revision change notices",
        ["col.reviewOutstanding"] = "Outstanding disciplines",
        ["col.reviewBlocking"] = "Blocking findings",
        ["col.reviewWaiting"] = "Days waiting",
        ["col.changePending"] = "Incomplete assessments",
        ["col.changeScope"] = "Scope",
        ["digest.subject_reviewPackages"] = "{0} multidisciplinary reviews",
        ["digest.subject_changes"] = "{0} revision changes",
        ["digest.section.reviewPackages"] = "Multidisciplinary reviews",
        ["digest.section.changes"] = "Revision change assessments",
        ["review.digest_detail"] = "{0} — round {1}",
        ["change.digest_detail"] = "{0} — assessment due {1}",
        ["handoff.create_permission"] = "Only a project manager, relevant discipline lead or source owner can create this handoff.",
        ["handoff.sender"] = "Only the named sending owner can submit or respond.",
        ["handoff.receiver"] = "Only the named receiving owner can record this receipt.",
        ["handoff.self_receipt"] = "Independent receipt is required. A sender cannot accept their own submission, including after reassignment.",
        ["handoff.illegal_transition"] = "This handoff cannot take that step from its current state.",
        ["handoff.fixed"] = "This handoff is fixed. Its submitted evidence and receipt history must be preserved.",
        ["handoff.fixed_source"] = "Create another handoff for a different source deliverable.",
        ["handoff.fixed_purpose"] = "Create another handoff for a different purpose, receiving discipline, target or acceptance criteria.",
        ["handoff.active_member"] = "Choose an active project participant who can perform this action.",
        ["handoff.one_target"] = "Choose exactly one receiving task or deliverable.",
        ["handoff.reference_unavailable"] = "The referenced work or discipline is unavailable, cancelled or outside this project/receiving discipline.",
        ["handoff.source_changed"] = "The source record changed. Refresh and confirm its revision before submitting.",
        ["handoff.notification"] = "{0}: {1} — {2}",
        ["handoff.reassigned"] = "{0}: {1} — handoff owners reassigned",
        ["handoff.digest_detail"] = "{0}; needed by {1}",
        ["digest.section.handoffs"] = "Discipline handoffs",
        ["digest.subject_handoffs"] = "{0} discipline handoffs",
        ["export.handoffs"] = "{0} — Discipline handoffs",
        ["col.handoffSender"] = "Sending owner", ["col.handoffReceiver"] = "Receiving owner",
        ["col.handoffNeeded"] = "Needed by", ["col.handoffPromised"] = "Promised by", ["col.handoffPurpose"] = "Intended use",
        ["common.system"] = "System",
        ["role.PM"] = "Project Manager",
        ["role.TeamMember"] = "Team Member",
        ["role.Reviewer"] = "Reviewer",
        ["role.Viewer"] = "Viewer",
        ["follow.AllActivity"] = "All activity",
        ["follow.MyItemsOnly"] = "My items only",
        ["follow.Muted"] = "Muted",
        ["value.Setup"] = "Setup", ["value.Active"] = "Active", ["value.On Hold"] = "On Hold", ["value.Complete"] = "Complete",
        ["value.Archived"] = "Archived", ["value.Cancelled"] = "Cancelled",
        ["team.inactive_user"] = "Inactive people cannot be chosen.",
        ["team.primary_pm"] = "The primary Project Manager cannot be removed. Change the Project Manager first.",
        ["team.primary_pm_role"] = "The primary Project Manager must keep the Project Manager role.",
        ["team.discipline_in_use"] = "This discipline has deliverables or tasks that are not cancelled. Deactivate it instead.",
        ["project.number_format"] = "The project number does not match the organisation's format.",
        ["project.duplicate"] = "Project {0} ({1}) already uses this number.",
        ["project.duplicate_simple"] = "Another project already uses this number.",
        ["project.illegal_transition"] = "A project cannot move from {0} to {1}.",
        ["project.restricted_disabled"] = "Restricted projects are not enabled for this organisation.",
        ["link.invalid"] = "Enter a web address (https://…) or a network path (\\\\server\\share).",
        ["notify.collapsed"] = "{0} ({1} changes)",
        ["notify.added_to_project"] = "{0} added you to {1} {2} as {3}",
        ["notify.follow_hint"] = "You now follow this project ({0}). Change the level from the project header.",
        ["notify.removed_from_project"] = "{0} removed you from {1} {2}",
        ["notify.auto_added"] = "{0} was added to {1} as {2} because work was assigned to them",
        ["notify.became_lead"] = "You are Discipline Lead for {2} on {0} {1}",
        ["notify.staff_added"] = "{0} added {1} to {2} {3}",
        ["notify.staff_removed"] = "{0} removed {1} from {2} {3}",
        ["notify.staff_lead"] = "{0} made {1} a Discipline Lead on {2} {3}",
        ["notify.supervisor_added"] = "{0} added {1} to {2} as Team Member",
        ["notify.supervisor_removed"] = "{0} removed {1} from {2} ({3} items reassigned)",
        ["notify.new_pm"] = "You are now the Project Manager of {0} {1}",
        ["notify.project_status"] = "{0} changed {1} {2} to {3}",
        ["notify.batched_assignments"] = "You were assigned {0} tasks on {1} {2}",
        ["email.open"] = "Open in the Hub",
        ["email.footer"] = "This message was sent by the Coordination Hub. Replies are not read; change your notification preferences in the Hub.",
        ["milestone.use_change_date"] = "Use Change date to move a dated milestone; the reason and slip are recorded.",
        ["milestone.closed"] = "This milestone is complete or cancelled.",
        ["milestone.too_early"] = "A milestone can be completed only within 7 days of its date. Move the date first.",
        ["milestone.future_completion"] = "The date cannot be in the future.",
        ["milestone.open_deliverables"] = "{0} targeted deliverables are not issued. Confirm to complete the milestone anyway.",
        ["milestone.completed_with_open"] = "Completed with deliverables not issued: {0}",
        ["milestone.not_complete"] = "Only a complete milestone can be reopened.",
        ["milestone.in_use"] = "Deliverables or tasks target this milestone. Cancel it instead, or retarget them first.",
        ["deliverable.inactive_discipline"] = "This discipline is inactive on the project.",
        ["deliverable.start_after_due"] = "The start date must be on or before the due date.",
        ["deliverable.after_milestone"] = "{0} is due after its milestone {1} ({2}); it is flagged Date Inconsistent.",
        ["deliverable.confirm_move_tasks"] = "Changing the discipline also moves its {0} tasks to the new discipline. Confirm to continue.",
        ["deliverable.use_issue"] = "Use Issue deliverable to record the issue date, revision and recipient.",
        ["deliverable.illegal_transition"] = "A deliverable cannot move from {0} to {1}.",
        ["deliverable.reviewer_required"] = "Choose a reviewer before moving the deliverable to In Review.",
        ["deliverable.issue_not_ready"] = "Only a deliverable that is Ready to Issue can be issued.",
        ["deliverable.open_tasks"] = "{0} tasks are still open. They stay open and are flagged. Confirm to issue anyway.",
        ["deliverable.issued_with_open"] = "Issued with open tasks: {0}",
        ["deliverable.has_tasks"] = "A deliverable with tasks cannot be deleted. Cancel it, or move its tasks first.",
        ["guard.ready_to_issue_needs_review"] = "Cannot set Ready to Issue: this deliverable requires review and has not been In Review.",
        ["notify.milestone_moved"] = "{0} moved {1} {2} from {3} to {4} ({5} days)",
        ["notify.deliverable_owned"] = "{0} made you owner of {1} {2}",
        ["notify.reassigned_away"] = "{0} reassigned {1} {2} to someone else",
        ["notify.deliverable_revision"] = "{0} returned {1} {2} for revision",
        ["notify.deliverable_review"] = "{0} moved {1} {2} to In Review",
        ["task.other_project"] = "A task can only belong to a deliverable in its own project.",
        ["task.self_review"] = "The reviewer cannot be the assignee (self-review is off).",
        ["task.milestone_or_deliverable"] = "A task targets a milestone directly only when it has no deliverable.",
        ["task.after_deliverable"] = "{0} is due after its deliverable {1} ({2}); it is flagged Date Inconsistent.",
        ["task.progress_steps"] = "Progress is 0 to 100 in steps of 10.",
        ["task.complete_is_100"] = "A complete task is always at 100 %.",
        ["task.requires_review_hint"] = "This task requires review: set Ready for Review instead of Complete.",
        ["task.illegal_transition"] = "A task cannot move from {0} to {1}.",
        ["task.reviewer_required"] = "Choose a reviewer before setting Ready for Review.",
        ["task.started_blocked"] = "{0} is blocked; it was started anyway.",
        ["task.start_needs"] = "{0} is {1}{2}. Starting work that is not Ready needs {3}.{4}",
        ["task.start_not_assessed"] = " (no readiness assessment has been recorded)",
        ["task.start_not_evaluated"] = " (readiness could not be evaluated: {0})",
        ["task.start_reasons"] = " ({0})",
        ["task.start_blocked"] = "blocked: {0}",
        ["task.start_unknown"] = "needs assessment: {0}",
        ["task.start_need.acknowledgement"] = "your acknowledgement of this readiness warning",
        ["task.start_need.reason"] = "a reason of at least 5 characters",
        ["task.start_need.authorisation"] = "a start authorisation from the Project Manager or the Discipline Lead",
        ["task.start_not_needed"] = "{0} is {1}; it starts without an authorisation.",
        ["task.start_not_started"] = "Only a Not Started task can be authorised to start.",
        ["task.start_ack"] = "Acknowledge the readiness warning before authorising the start.",
        ["task.start_auth_unusable"] = " The start authorisation recorded by {0} can no longer be used because they are no longer an active Project Manager or Discipline Lead for this work.",
        ["notify.task_start_authorised"] = "{0} authorised starting {1} {2} while it is {3}",
        ["dep.same_project"] = "Both tasks must be in the same project.",
        ["dep.self"] = "An item cannot depend on itself.", ["holiday.exists"] = "That day is already a holiday on this calendar.", ["error.idempotency_reused"] = "That Idempotency-Key was already used for a different request.", ["dep.one_end"] = "Choose either the predecessor or the successor.", ["dep.lag"] = "Lag is between 0 and 365 days.",
        ["dep.duplicate"] = "This dependency already exists.",
        ["dep.cycle"] = "This would create a loop: {0}.",
        ["dep.would_cycle"] = "Would create a loop",
        ["dep.successor_complete"] = "{0} is already complete.",
        ["dep.predecessor_complete"] = "{0} is already complete; the dependency is recorded for reference.",
        ["notify.task_assigned"] = "{0} assigned you {1} {2}",
        ["notify.reviewer_set"] = "{0} made you reviewer of {1} {2}",
        ["notify.reviewer_removed"] = "{0} changed the reviewer of {1} {2}; you are no longer reviewing it",
        ["notify.due_changed"] = "{0} changed the due date of {1} {2}: {3} → {4}",
        ["notify.collaborator_added"] = "{0} added you as a collaborator on {1} {2}",
        ["notify.review_requested"] = "{0} asked you to review {1} {2}",
        ["notify.review_requested_round"] = "{0} asked you to review {1} {2} (round {3})",
        ["notify.review_started"] = "{0} started reviewing {1} {2}",
        ["notify.review_approved"] = "{0} approved {1} {2}",
        ["notify.review_revision"] = "{0} returned {1} {2} for revision (round {3})",
        ["notify.dependency_removed"] = "{0} removed the dependency {1} → {2} {3}",
        ["notify.dependency_removed_deleted"] = "{0} deleted {1} {2}; dependencies on it were removed",
        ["notify.bulk_assigned"] = "{0} assigned you {1} tasks on {2}",
        ["notify.bulk_due"] = "{0} changed the due dates of {1} of your tasks on {2}",
        ["notify.task_blocked"] = "Your task {0} {1} is blocked by {2}{3}",
        ["notify.overdue_word"] = " (overdue)",
        ["notify.task_unblocked"] = "{0} {1} is no longer waiting — you can start",
        ["notify.blocking_overdue"] = "{0} {1} is overdue and blocking others: {2}",
        ["notify.attention_critical"] = "{0} {1}: {2} — {3}",
        ["notify.milestone_status"] = "{0} {1} is now {2}",
        ["notify.decision_overdue"] = "Decision {0} {1} was required by {2} and is overdue",
        ["notify.decision_assigned"] = "{0} made you owner of decision {1} {2}",
        ["notify.decision_recorded"] = "{0} recorded decision {1} {2}",
        ["decision.one_owner"] = "Choose exactly one owner: a person or an external party.",
        ["decision.blocks_tasks_only"] = "Only tasks can be blocked by a decision; link deliverables and milestones as related.",
        ["decision.other_project"] = "Linked items must belong to the decision's project.",
        ["decision.link_exists"] = "That item is already linked to this decision.",
        ["decision.date_closed"] = "The required-by date of a closed decision cannot change.",
        ["decision.future_date"] = "The decision date cannot be in the future.",
        ["decision.defer_future"] = "The new required-by date must be later than today.",
        ["decision.illegal_transition"] = "A decision cannot move from {0} to {1}.",
        ["notify.override_expired"] = "The health override on {0} {1} ({2}) expired",
        ["perm.comment_edit_window"] = "Comments can be edited for 15 minutes after posting; post a follow-up instead.",
        ["attention.snooze_days"] = "Snooze for 1 to 30 days.",
        ["notify.mention"] = "{0} mentioned you on {1} {2}",
        ["notify.comment"] = "{0} commented on {1} {2}",
        ["comment.locked"] = "This comment can no longer be edited.",
        ["comment.mention_restricted"] = "{0} cannot see this restricted project, so they cannot be mentioned.",
        ["digest.subject"] = "Hub digest — {0}",
        ["digest.subject_overdue"] = "{0} overdue", ["digest.subject_review"] = "{0} review", ["digest.subject_reviews"] = "{0} reviews",
        ["digest.subject_blocked"] = "{0} blocked", ["digest.subject_dueSoon"] = "{0} due soon", ["digest.subject_decisions"] = "{0} decisions",
        ["digest.subject_attention"] = "{0} attention items", ["digest.subject_milestones"] = "{0} milestones approaching",
        ["digest.subject_update"] = "{0} project update", ["digest.subject_updates"] = "{0} project updates",
        ["digest.greeting"] = "Good morning {0} — what needs you on {1}.",
        ["digest.section.overdue"] = "Overdue", ["digest.section.dueSoon"] = "Due soon", ["digest.section.blocked"] = "Blocked",
        ["digest.section.reviews"] = "Reviews waiting on you", ["digest.section.decisions"] = "Decisions you own or requested",
        ["digest.section.attention"] = "Needs attention on your projects", ["digest.section.milestones"] = "Milestones approaching",
        ["digest.section.updates"] = "Project updates", ["digest.section.staff"] = "My staff",
        ["digest.staff_detail"] = "{0} overdue, {1} blocked, {2} reviews waiting", ["digest.subject_staff"] = "{0} staff items",
        ["digest.overdue_detail"] = "due {0}, {1} days overdue", ["digest.blocked_detail"] = "blocked by {0}", ["digest.review_detail"] = "{0}, due {1}",
        ["digest.decision_overdue"] = "required by {0}, {1} days overdue", ["digest.decision_due"] = "required by {0}", ["digest.due_detail"] = "due {0}",
        ["digest.milestone_detail"] = "{0}, in {1} days {2}",
        ["digest.more"] = "and {0} more:", ["digest.update_counts"] = "{0} changes ({1})", ["digest.following"] = "All changes:",
        ["digest.type.status"] = "status", ["digest.type.assignment"] = "assignment", ["digest.type.date"] = "date", ["digest.type.decision"] = "decision", ["digest.type.other"] = "other",
        ["digest.action.Created"] = "created", ["digest.action.Updated"] = "changed", ["digest.action.StatusChanged"] = "changed the status of",
        ["digest.action.Assigned"] = "assigned", ["digest.action.DateChanged"] = "changed dates on", ["digest.action.Issued"] = "issued",
        ["digest.action.Deleted"] = "deleted", ["digest.action.Decided"] = "decided", ["digest.action.Reopened"] = "reopened", ["digest.action.Cascade"] = "shifted",
        ["digest.footer"] = "My Work: {0}\nChange or turn off this digest: {1}\n\nThis message was sent by the Coordination Hub. Replies are not read.",
        ["perm.person_work"] = "You can see only your own work, your direct reports' work, or your project members' tasks on projects you manage.",
        ["perm.all_staff"] = "Only Executives and Administrators can see all staff.",
        ["error.not_found"] = "Not found.",
        ["error.validation"] = "One or more fields are invalid.",
        ["error.invalid"] = "Enter a valid value.",
        ["error.required"] = "Required.",
        ["error.too_long"] = "Must be {0} characters or fewer.",
        ["error.one_of"] = "Must be one of: {0}.",
        ["error.reason_required"] = "Give a reason of at least 5 characters.",
        ["error.concurrency"] = "This item was changed by someone else. Reload to see the latest version.",
        ["error.concurrency_by"] = "This item was changed by {0} {1}. Reload to see the latest version.",
        ["error.duplicate"] = "That value already exists.",
        ["error.bad_json"] = "The request body is not valid JSON.",
        ["error.server"] = "Something went wrong. Quote the trace ID when you contact support.",
        ["error.inactive_account"] = "Your Hub account is inactive. Contact a System Administrator.",
        ["error.if_match"] = "Send the version you read (If-Match header or rowVersion).",
        ["error.date"] = "Enter a valid date.",
        ["error.positive"] = "Must be a positive number.",
        ["perm.admin"] = "Only a System Administrator can do this.",
        ["perm.read_only"] = "Read Only accounts cannot make changes.",
        ["perm.pm"] = "Only the Project Manager can do this.",
        ["perm.pm_or_dl"] = "Only the Project Manager or the Discipline Lead can do this.",
        ["perm.dl_own"] = "Only the Project Manager or the {0} lead can do this. Ask the PM or the discipline lead.",
        ["perm.create_project"] = "Only people with the Project Manager role can create projects. An Admin can grant it.",
        ["perm.project_read_only"] = "This project is {0} and read-only.",
        ["perm.not_member"] = "Only members of this project can do this.",
        ["perm.comment"] = "You cannot comment on this project.",
        ["perm.task_edit"] = "Only the assignee, a collaborator, the creator, the Discipline Lead or the PM can edit this task.",
        ["perm.task_assign"] = "Only the Project Manager or the Discipline Lead can reassign this task.",
        ["perm.task_due"] = "Only the assignee, the Discipline Lead or the PM can change the due date.",
        ["perm.transition"] = "You cannot move this item to {0}.",
        ["perm.supervisor"] = "Only this person's supervisor can do this.",
        ["perm.staff"] = "Only Supervisors, Executives and Admins can open My Staff.",
        ["perm.portfolio"] = "Only Executives, Supervisors, Project Managers and Admins can open the portfolio.",
        ["perm.workload"] = "You cannot open the workload view.",
        ["perm.templates"] = "Only Admins and Template Editors can edit templates.",
        ["perm.owner"] = "Only the owner or the Project Manager can do this.",
        ["perm.time_entry"] = "Only the person who entered these hours can change them.",
        ["admin.last_admin"] = "This is the only active System Administrator. Give another person the Admin role first.",
        ["admin.self_supervisor"] = "A person cannot be their own supervisor.",
        ["admin.in_use"] = "In use by {0} projects. It will be hidden from pickers; existing items keep it.",
        ["admin.create_user_local_only"] = "People are added when they first sign in with Microsoft. Creating them here is only for password sign-in.",
        ["admin.user_exists"] = "Someone with this email is already in the Hub. Find them in the list, including inactive people.",
        ["admin.email_invalid"] = "Enter one email address, such as name@example.com.",
        ["setting.int"] = "Enter a whole number from 0 to 3650.",
        ["setting.bool"] = "Must be on or off.",
        ["setting.time"] = "Use 24-hour HH:mm.",
        ["setting.timezone"] = "Unknown time zone.",
        ["setting.regex"] = "Not a valid regular expression.",
        ["setting.channels"] = "Choose in-app and email on or off.",
        ["setting.text"] = "Enter up to 200 characters.",
        ["setting.unknown"] = "Unknown setting.",
        // Reports and exports (§19, packet 009)
        ["report.allVisible"] = "All projects you can see (not archived or cancelled)",
        ["report.tasks-due-this-week"] = "Tasks Due This Week", ["report.tasks-due-this-week.about"] = "Open tasks due Monday to Sunday of the chosen week.",
        ["report.overdue-tasks"] = "Overdue Tasks", ["report.overdue-tasks.about"] = "Tasks past their due date, with what they hold up.",
        ["report.blocked-tasks"] = "Blocked Tasks", ["report.blocked-tasks.about"] = "Tasks that cannot proceed and what blocks them.",
        ["report.tasks-blocking-others"] = "Tasks Blocking Others", ["report.tasks-blocking-others.about"] = "Tasks whose successors are waiting or blocked on them.",
        ["report.upcoming-deliverables"] = "Upcoming Deliverables", ["report.upcoming-deliverables.about"] = "Open deliverables due in the coming days.",
        ["report.deliverable-status-by-project"] = "Deliverable Status by Project", ["report.deliverable-status-by-project.about"] = "Every deliverable by project with status, due and issue dates.",
        ["report.upcoming-milestones"] = "Upcoming Milestones", ["report.upcoming-milestones.about"] = "Milestones in the coming days with readiness and slip.",
        ["report.open-decisions"] = "Open Decisions", ["report.open-decisions.about"] = "Decisions still to be made, by required-by date.",
        ["report.review-queue"] = "Review Queue", ["report.review-queue.about"] = "Tasks and deliverables waiting for review, longest first.",
        ["report.stale-work"] = "Stale Work", ["report.stale-work.about"] = "Open tasks with no activity for a number of days.",
        ["report.project-activity-log"] = "Project Activity Log", ["report.project-activity-log.about"] = "Every recorded change on one project.",
        ["report.staff-assignments"] = "Staff Assignments", ["report.staff-assignments.about"] = "Your staff's project assignments with their open and overdue work.",
        ["param.projectId"] = "Projects", ["param.disciplineId"] = "Discipline", ["param.assigneeId"] = "Assignee", ["param.week"] = "Week of",
        ["param.mine"] = "My tasks only", ["param.minDaysOverdue"] = "Minimum days overdue", ["param.blockerType"] = "Blocked by", ["param.daysAhead"] = "Days ahead",
        ["param.type"] = "Milestone type", ["param.ownerType"] = "Owner type", ["param.overdueOnly"] = "Overdue only", ["param.reviewerId"] = "Reviewer",
        ["param.days"] = "Days without activity", ["param.from"] = "From", ["param.to"] = "To", ["param.category"] = "Action type", ["param.scope"] = "Staff",
        ["param.officeId"] = "Office", ["param.role"] = "Role",
        ["opt.task"] = "A task", ["opt.decision"] = "A decision", ["opt.manual"] = "A manual block", ["opt.internal"] = "Internal", ["opt.external"] = "External",
        ["opt.client"] = "Client", ["opt.direct"] = "My direct reports", ["opt.all"] = "All staff", ["opt.PM"] = "Project Manager", ["opt.TeamMember"] = "Team Member",
        ["opt.Reviewer"] = "Reviewer", ["opt.Viewer"] = "Viewer", ["opt.status"] = "Status changes", ["opt.assignment"] = "Assignments", ["opt.date"] = "Date changes",
        ["opt.deletion"] = "Deletions", ["opt.creation"] = "Creations", ["opt.comment"] = "Comments", ["opt.health"] = "Health", ["opt.dependency"] = "Dependencies",
        ["opt.structure"] = "Structure",
        ["opt.Kickoff"] = "Kickoff", ["opt.Field Work"] = "Field Work", ["opt.Design Submission"] = "Design Submission", ["opt.Client Workshop"] = "Client Workshop",
        ["opt.Permit Submission"] = "Permit Submission", ["opt.Tender"] = "Tender", ["opt.Construction"] = "Construction", ["opt.IFC"] = "IFC",
        ["opt.Record Drawings"] = "Record Drawings", ["opt.Closeout"] = "Closeout", ["opt.Other"] = "Other",
        ["col.key"] = "Key", ["col.task"] = "Task", ["col.project"] = "Project", ["col.projectName"] = "Project name", ["col.deliverable"] = "Deliverable",
        ["col.discipline"] = "Discipline", ["col.assignee"] = "Assignee", ["col.reviewer"] = "Reviewer", ["col.owner"] = "Owner", ["col.due"] = "Due",
        ["col.status"] = "Status", ["col.indicators"] = "Indicators", ["col.daysOverdue"] = "Days overdue", ["col.blockingCount"] = "Blocking",
        ["col.affectedMilestones"] = "Affected milestones", ["col.blockedSince"] = "Blocked since", ["col.daysBlocked"] = "Days blocked", ["col.blockers"] = "Blocked by",
        ["col.successors"] = "Successors", ["col.successorMilestones"] = "Successors' milestones", ["col.milestone"] = "Milestone", ["col.progress"] = "Progress",
        ["col.issued"] = "Issued", ["col.revision"] = "Revision", ["col.type"] = "Type", ["col.date"] = "Date", ["col.slip"] = "Slip (days)",
        ["col.deliverablesIssued"] = "Deliverables issued", ["col.openTasks"] = "Open tasks", ["col.overdueTasks"] = "Overdue tasks", ["col.subject"] = "Subject",
        ["col.requested"] = "Requested", ["col.requiredBy"] = "Required by", ["col.days"] = "Days", ["col.impact"] = "Impact", ["col.item"] = "Item",
        ["col.readySince"] = "Ready since", ["col.daysWaiting"] = "Days waiting", ["col.round"] = "Round", ["col.lastActivity"] = "Last activity",
        ["col.timestamp"] = "Timestamp", ["col.actor"] = "Actor", ["col.action"] = "Action", ["col.change"] = "Change", ["col.reason"] = "Reason",
        ["col.person"] = "Person", ["col.projectStatus"] = "Project status", ["col.roles"] = "Roles", ["col.primaryDiscipline"] = "Primary discipline",
        ["col.addedOn"] = "Added on", ["col.addedBy"] = "Added by", ["col.name"] = "Name", ["col.client"] = "Client", ["col.pm"] = "Project Manager",
        ["col.health"] = "Health", ["col.phase"] = "Phase", ["col.office"] = "Office", ["col.priority"] = "Priority", ["col.start"] = "Start",
        ["col.estimate"] = "Estimated hours", ["col.requestedBy"] = "Requested by", ["col.decision"] = "Decision", ["col.decisionDate"] = "Decision date",
        ["col.nextMilestone"] = "Next milestone", ["col.target"] = "Target completion", ["col.source"] = "Source",
        ["ind.overdue"] = "Overdue {0}d", ["ind.atRisk"] = "At risk", ["ind.blocked"] = "Blocked", ["ind.waiting"] = "Waiting", ["ind.blocking"] = "Blocking {0}",
        ["ind.dueSoon"] = "Due soon", ["ind.stale"] = "Stale", ["ind.unassigned"] = "Unassigned", ["ind.dateInconsistent"] = "Date inconsistent",
        ["ind.inactiveOwner"] = "Inactive owner", ["ind.heldPastDue"] = "Held past due", ["ind.overdueWord"] = "overdue",
        ["itemType.Task"] = "Task", ["itemType.Deliverable"] = "Deliverable",
        ["export.too_large"] = "More than {0} rows: export one project at a time.", ["export.generated"] = "Generated",
        ["export.tasks"] = "Tasks {0}", ["export.deliverables"] = "Deliverables {0}", ["export.decisions"] = "Decisions {0}", ["export.milestones"] = "Milestones {0}",
        ["export.projects"] = "Projects", ["export.activity"] = "Activity {0}",
        ["copy.reason"] = "Copied from the structure of {0}",
        ["report.projects-at-risk"] = "Projects At Risk", ["report.projects-at-risk.about"] = "Active projects whose computed or reported health is Red or Yellow, and why.",
        ["report.health-history"] = "Health History", ["report.health-history.about"] = "Nightly computed and reported health by project.",
        ["param.pmId"] = "Project Manager", ["opt.Red"] = "Red", ["opt.Yellow"] = "Yellow", ["nav.portfolio"] = "Portfolio",
        ["col.computedHealth"] = "Computed health", ["col.reportedHealth"] = "Reported health", ["col.why"] = "Why", ["col.overrideNote"] = "Override note",
        ["col.nextMilestoneDate"] = "Next milestone date", ["col.nextSubmission"] = "Next submission", ["col.nextSubmissionDate"] = "Submission date",
        ["col.blockedTasks"] = "Blocked tasks", ["col.overdueDecisions"] = "Overdue decisions", ["col.highIssues"] = "High issues", ["col.critical"] = "Critical",
        ["col.warning"] = "Warning",
        ["reassign.same_person"] = "Choose someone else to take the work.", ["reassign.not_open"] = "Some items are no longer open for this person. Refresh the list.",
        ["reassign.reason"] = "Work reassigned from {0}",
        ["notify.work_reassigned"] = "{0} reassigned {1} items of {2} on {3} to {4}",
        ["notify.task_moved"] = "{0} reassigned {1} {2} from {3} to {4}",
        ["view.project_needed"] = "A shared view belongs to a project.",
        ["time.range"] = "Choose a range of at most a year.", ["time.hours"] = "Enter hours greater than 0 and at most 24.",
        ["time.hours_precision"] = "Use at most two decimal places.", ["time.day_over"] = "That would take the day past 24 hours; at most {0} more hours fit.",
        ["time.task_fixed"] = "An entry stays on its task; delete it and add a new one instead.", ["time.total"] = "Total", ["nav.time"] = "Time",
        ["time.entries"] = "Entries", ["time.scope.mine"] = "Mine", ["time.scope.all"] = "Everyone I can review", ["opt.mine"] = "Mine", ["opt.team"] = "Everyone I can review",
        ["col.hours"] = "Hours", ["col.note"] = "Note", ["param.userId"] = "Person", ["param.taskId"] = "Task",
        ["report.task-hours"] = "Task Hours", ["report.task-hours.about"] = "Actual hours recorded against tasks, by date and person.",
        ["workspace.duplicate"] = "You already have a workspace with that name.", ["workspace.projects"] = "Choose between 1 and 100 projects.",
        ["workspace.not_visible"] = "One of those projects is not available to you.", ["workspace.task_outside"] = "Those cards are not all in this workspace's projects.",
        ["col.toDecide"] = "What must be decided", ["col.timing"] = "Days until or overdue", ["decision.the_client"] = "the client",
        ["decision.none_for_client"] = "No open decisions are owned by {0}, so there is nothing to export.",
        ["decision.days_overdue"] = "{0} days overdue", ["decision.due_today"] = "Needed today", ["decision.days_left"] = "In {0} days",
        ["decision.client_export"] = "Decisions needed from {0} — {1}",
        ["risk.level"] = "Choose 1, 2 or 3.", ["risk.illegal_transition"] = "A risk cannot move from {0} to {1}.",
        ["risk.realised_needs_issue"] = "Create or choose the issue this risk became.", ["risk.issue_has_origin"] = "That issue already records another risk as its origin.",
        ["issue.illegal_transition"] = "An issue cannot move from {0} to {1}.", ["issue.future_raised"] = "The date raised cannot be in the future.",
        ["issue.target_before_raised"] = "The target date cannot be before the date raised.", ["issue.future_resolved"] = "The resolved date cannot be in the future.",
        ["issue.resolution_when_resolved"] = "The resolution is recorded when the issue is resolved.",
        ["export.risks"] = "Risk register {0}", ["export.issues"] = "Issue register {0}",
        ["col.title"] = "Title", ["col.severity"] = "Severity", ["col.score"] = "Score", ["col.probability"] = "Probability", ["col.impactScore"] = "Impact",
        ["col.reviewDate"] = "Review date", ["col.mitigation"] = "Mitigation", ["col.trigger"] = "Trigger indicator", ["col.realisedAs"] = "Realised as",
        ["col.raisedBy"] = "Raised by", ["col.dateRaised"] = "Date raised", ["col.targetDate"] = "Target resolution", ["col.resolvedDate"] = "Resolved",
        ["col.resolution"] = "Resolution", ["col.originRisk"] = "From risk", ["itemType.Risk"] = "Risk", ["itemType.Issue"] = "Issue",
        ["report.open-issues-high-risks"] = "Open Issues / High Risks",
        ["report.open-issues-high-risks.about"] = "Open issues and open risks, most severe first. Without a severity, every open issue and the High risks.",
        ["param.severity"] = "Severity", ["opt.High"] = "High", ["opt.Medium"] = "Medium", ["opt.Low"] = "Low",
        ["health.Red"] = "Red", ["health.Yellow"] = "Yellow", ["health.Green"] = "Green", ["health.Grey"] = "Grey",
        ["weekly.subject"] = "Hub weekly summary — {0}{1} · {2} overdue", ["weekly.subject_red"] = " · {0} Red",
        ["weekly.project1"] = "1 project", ["weekly.projectN"] = "{0} projects",
        ["weekly.greeting1"] = "Hi {0}, here is the week for your Active project, {2}.", ["weekly.greeting"] = "Hi {0}, here is the week for your {1} Active projects, {2}.", ["weekly.health"] = "Health: {0} computed · {1} reported",
        ["weekly.next_submission"] = "Next submission: {0} · {1} (in {2} days)", ["weekly.no_submission"] = "No submission planned",
        ["weekly.counts"] = "Overdue tasks: {0} · Blocked tasks: {1} · Overdue decisions: {2}", ["weekly.attention"] = "Needs attention:",
        ["weekly.changes"] = "Changes since the last summary: {0} ({1})", ["weekly.no_changes"] = "No changes by others since the last summary",
        ["weekly.footer"] = "You receive this because you manage these projects. Turn it off in your preferences: {0}",
        ["meeting.coordination_title"] = "Weekly Coordination — {0}", ["error.url"] = "Enter a full web address starting with https://.",
        ["action.one_owner"] = "Choose one owner of the chosen kind: a person, a discipline or an external party.",
        ["action.no_lead_warning"] = "That discipline has no lead, so the action is flagged to the PM.",
        ["action.illegal_transition"] = "An action cannot move from {0} to {1}.", ["action.follows_task"] = "This action follows its task {0}; change the task instead.",
        ["action.follows_task_edit"] = "This action follows the task it became; that link stays.", ["action.convert_open"] = "Only an open action can become a task.",
        ["action.already_converted"] = "This action is already a task.", ["action.converted_from"] = "From action {0} of {1} ({2}).",
        ["notify.action_assigned"] = "{0} gave you action {1} {2}", ["notify.action_discipline"] = "{0} gave the {3} discipline action {1} {2}",
        ["notify.action_no_lead"] = "{0} gave the {3} discipline action {1} {2}; the discipline has no lead",
        ["export.actions"] = "Meeting actions {0}", ["col.actionText"] = "Action", ["col.meeting"] = "Meeting", ["col.meetingDate"] = "Meeting date", ["col.ownerType"] = "Owner type",
        ["opt.User"] = "Person", ["opt.Discipline"] = "Discipline", ["opt.External Party"] = "External party", ["itemType.Action"] = "Action",
        ["report.meeting-actions-outstanding"] = "Meeting Actions Outstanding",
        ["report.meeting-actions-outstanding.about"] = "Open actions from project meetings, by due date, with who owns them.",
        ["template.not_published"] = "Only a published template can be retired.", ["template.not_draft"] = "Only a draft changes; start a new draft from this version.",
        ["template.bad_ref"] = "A reference in the template structure is missing or repeated.", ["template.bad_discipline"] = "Each item needs one of the template's disciplines, each listed once.",
        ["template.offset"] = "Offsets are at most ten years either way.", ["template.estimate"] = "Estimates are between 0 and 10,000 hours.",
        ["template.bad_dependency"] = "A task cannot depend on itself, or on the same task twice.", ["template.cycle"] = "These dependencies form a loop, so the tasks could never be scheduled.",
        ["template.empty"] = "Add at least one milestone or deliverable before publishing.",
        ["template.unavailable"] = "This template has been retired or replaced since you chose it. Choose a published template and try again.",
        ["template.one_source"] = "Start from a template or from another project, not both.",
        ["template.basis_units"] = "A numeric value needs its units.",
        ["template.basis_in_use"] = "{0} has design basis suggestions ({1}). Remove those suggestions first.",
        ["template.created_reason"] = "From {0} v{1}: {2} milestones, {3} deliverables, {4} tasks, {5} dependencies",
        ["template.pack_reason"] = "From {0} v{1}: {2} deliverables and {3} tasks",
        ["report.pilot-measures"] = "Pilot measures", ["report.pilot-measures.about"] = "Weekly readings of the pilot goals on chosen projects: coordination reviews, tasks without an owner or due date, blocked tasks, and people updating task status.",
        ["param.weeks"] = "Weeks", ["col.pilotWeek"] = "Week of", ["col.coordinationReviews"] = "Coordination reviews (G1)", ["col.unassignedOpen"] = "Open tasks without owner (G2)",
        ["col.noDueDateOpen"] = "Open tasks without due date (G2)", ["col.blockedTasks"] = "Blocked tasks (G3)", ["col.peopleWithWork"] = "People with open tasks",
        ["col.statusUpdaters"] = "Changed a task status (G4)", ["col.statusUpdatersPct"] = "Share changing status (G4)",
        ["home.range"] = "Choose a range of at most a year, ending after it starts.",
        ["calendar.cancelled"] = "This event was cancelled.", ["calendar.range"] = "Choose a range of at most three months.",
        ["calendar.project_required"] = "Meetings and site work belong to a project.", ["calendar.end_before_start"] = "The end must be after the start.",
        ["nav.workload"] = "Workload", ["report.workload-employee"] = "Workload by Employee", ["report.workload-employee.about"] = "Each person's estimated hours per week against capacity, with open, unestimated and overdue tasks.",
        ["report.workload-discipline"] = "Workload by Discipline", ["report.workload-discipline.about"] = "Estimated hours per week by discipline.",
        ["param.supervisorId"] = "Supervisor", ["col.supervisor"] = "Supervisor", ["col.capacity"] = "Capacity (h/week)", ["col.weekOf"] = "Week of {0}",
        ["col.forecast"] = "Forecast (h)", ["col.available"] = "Available (h)", ["col.confirmed"] = "Confirmed reservation (h)",
        ["col.proposed"] = "Proposed request (h)", ["col.committed"] = "Committed load (h)", ["col.partialScope"] = "Scope",
        ["workload.partial"] = "Partial project scope", ["workload.complete"] = "All permitted projects",
        ["notify.allocation_changed"] = "Allocation for {0} is {1}",
        ["notify.submission_changed"] = "Submission {0} is {1}",
        ["notify.issue_verification_requested"] = "Verify the proposed resolution for issue {0}",
        ["notify.issue_verification_outcome"] = "Issue {0} verification was {1}",
        ["notify.issue_affected_discipline"] = "Issue {0} affects your discipline: {1}",
        ["notify.constraint_assigned"] = "Remove the {0} constraint on {1}",
        ["notify.constraint_proposed"] = "Verify the proposed removal of the {0} constraint on {1}",
        ["notify.constraint_outcome"] = "The {0} constraint on {1} is {2}",
        ["notify.commitment_proposed"] = "Confirm the proposed weekly commitment for {0}",
        ["notify.commitment_changed"] = "Weekly commitment for {0} is {1}",
        ["notify.basis_replaced"] = "Design basis {0} was replaced; assess the impact on your work",
        ["notify.basis_withdrawn"] = "Design basis {0} was withdrawn; assess the impact on your work",
        ["notify.basis_decision_reopened"] = "Decision {0} was reopened; assess design basis {1}, which your work uses",
        ["notify.basis_conflict"] = "Design basis {0} conflicts with another confirmed value",
        ["readiness.week_start"] = "A coordination week for this project starts on {0}.",
        ["readiness.linked_unavailable"] = "Linked record unavailable",
        ["export.readinessConstraints"] = "{0} — Readiness constraints", ["export.readyOutputs"] = "{0} — Ready outputs",
        ["export.weeklyCommitments"] = "{0} — Weekly commitments",
        ["col.constraintCategory"] = "Category", ["col.description"] = "Description", ["col.removalOwner"] = "Removal owner",
        ["col.affectedOwner"] = "Affected work owner", ["col.neededBy"] = "Needed by", ["col.linkedRecord"] = "Linked record",
        ["col.sourceEvidence"] = "Source evidence", ["col.intendedOutput"] = "Intended output", ["col.completionCriteria"] = "Completion criteria",
        ["col.readiness"] = "Readiness", ["col.performer"] = "Performer", ["col.weekStart"] = "Week start", ["col.promiseTargetDate"] = "Target date",
        ["col.readinessAtCommit"] = "Readiness at commitment", ["col.snapshotAt"] = "Snapshot captured", ["col.completionEvidence"] = "Completion evidence",
        ["param.list"] = "List",
        ["readiness.prerequisite_self"] = "This package lists the work's own deliverable, so it cannot be a prerequisite for that work.",
        ["basis.duplicate"] = "A basis entry with this title, discipline and scope already exists. Inspect it before creating another.",
        ["basis.units"] = "Numeric design criteria need explicit units before confirmation.",
        ["basis.independent"] = "A responsible Discipline Lead or assigned independent approver must confirm this version.",
        ["basis.proposed"] = "This basis version is not an active proposal.",
        ["basis.edit_linked"] = "This proposal has an approved assumption disposition or consuming work. Withdraw it and create a new proposal instead of changing the recorded basis.",
        ["basis.current"] = "This basis version is no longer the current registered version.",
        ["basis.source"] = "Source evidence and rationale are required for confirmation.",
        ["basis.assumption"] = "An unconfirmed assumption needs an approved, unexpired disposition before use.",
        ["col.noDueDate"] = "No due date (h)", ["col.unestimated"] = "Unestimated", ["col.projectCount"] = "Projects", ["col.indicator"] = "Indicator",
        ["col.peopleCount"] = "People", ["col.week"] = "Week",
        ["workload.over"] = "Over-assigned", ["workload.under"] = "Under-assigned", ["workload.ok"] = "OK", ["workload.cluster"] = "Deadline cluster",
        ["param.q"] = "Search", ["param.status"] = "Status", ["param.priority"] = "Priority", ["param.deliverableId"] = "Deliverable", ["param.milestoneId"] = "Milestone",
        ["param.ownerId"] = "Owner", ["param.typeId"] = "Type", ["param.dueFrom"] = "Due from", ["param.dueTo"] = "Due to", ["param.indicator"] = "Indicator",
        ["param.impact"] = "Impact", ["param.requiredFrom"] = "Required from", ["param.requiredTo"] = "Required to", ["param.blocking"] = "Blocking work",
        ["param.sort"] = "Sort", ["param.group"] = "Group", ["param.itemType"] = "Item type", ["param.actorId"] = "Actor", ["param.importantOnly"] = "Important only",
        ["param.pmId"] = "Project Manager", ["param.clientId"] = "Client", ["param.phaseId"] = "Phase", ["param.health"] = "Health", ["param.includeArchived"] = "Include archived",
        ["param.ids"] = "Specific items", ["param.overdue"] = "Overdue", ["param.blocked"] = "Blocked", ["param.open"] = "Open only",
    };

    public static string Get(string key, params object[] args)
    {
        var s = En.TryGetValue(key, out var v) ? v : key;
        return args.Length == 0 ? s : string.Format(CultureInfo.InvariantCulture, s, args);
    }

    public static void Add(IReadOnlyDictionary<string, string> more) { foreach (var (k, v) in more) En[k] = v; }
}
