#!/usr/bin/env python3
"""Check that the Spec Kit packets under specs/ cover the whole product specification.

    python3 tools/trace_spec.py           write specs/TRACEABILITY.md and report gaps
    python3 tools/trace_spec.py --check   exit 1 if any ID or section is uncovered or unknown

Every requirement (FR-), acceptance (AC-), rule (G-, P-, TM-, M-, DL-, T-, R-, D-, DEC-, C-, DOC-,
ATT-, ASG-, RSK-, ISS-, MTG-), attention (A-), edge-case (E-), decision (Q), and goal (G1, T1) ID in
the specification must be cited by at least one packet's spec.md, and every section must be cited
by a packet or listed as a planning input.
"""
import pathlib
import re
import sys
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "Engineering-Project-Coordination-Hub-Specification.md"
PACKETS = sorted((ROOT / "specs").glob("[0-9][0-9][0-9]-*/spec.md"))
OUT = ROOT / "specs" / "TRACEABILITY.md"

RULE = r"(?:G|P|TM|M|DL|T|R|D|DEC|C|DOC|ATT|ASG|RSK|ISS|MTG|A|E)"
DASH = r"(?:\s+to\s+|\s*(?:…|\.\.|–|-)\s*)"
# Sections that feed /speckit-plan rather than a feature spec, and document scaffolding.
PLANNING = {"23", "24", "25", "26"}
REFERENCE = {"34", "35"}  # decisions and build order: carried by specs/README.md and packet assumptions


def expand(text):
    ids = set()
    for m in re.finditer(r"\b(FR-[A-Z]+)-(\d{2})\.\.(\d{2})\b", text):
        ids.update(f"{m[1]}-{n:02d}" for n in range(int(m[2]), int(m[3]) + 1))
    ids.update(re.findall(r"\bFR-[A-Z]+-\d{2}\b", text))
    ids.update(re.findall(r"\bAC-[A-Z]+-\d{2}\b", text))
    for m in re.finditer(rf"(?<![A-Za-z0-9-])({RULE})-(\d{{2}}){DASH}(?:\1-)?(\d{{2}})(?![0-9])", text):
        lo, hi = int(m[2]), int(m[3])
        if lo < hi <= lo + 40:
            ids.update(f"{m[1]}-{n:02d}" for n in range(lo, hi + 1))
    ids.update(f"{p}-{n}" for p, n in re.findall(rf"(?<![A-Za-z0-9-])({RULE})-(\d{{2}})(?![0-9])", text))
    for m in re.finditer(r"(?<![A-Za-z0-9])Q(\d{1,2})\s*(?:–|-|to)\s*Q(\d{1,2})(?![0-9])", text):
        ids.update(f"Q{n}" for n in range(int(m[1]), int(m[2]) + 1))
    ids.update(f"Q{n}" for n in re.findall(r"(?<![A-Za-z0-9])Q(\d{1,2})(?![0-9])", text))
    for m in re.finditer(r"(?<![A-Za-z0-9-])([GT])([1-6])\s*(?:–|-|to)\s*\1?([1-6])(?![0-9])", text):
        ids.update(f"{m[1]}{n}" for n in range(int(m[2]), int(m[3]) + 1))
    ids.update(f"{g}{n}" for g, n in re.findall(r"(?<![A-Za-z0-9-])([GT])([1-6])(?![0-9-])", text))
    return ids


def sections_cited(text):
    cited = set()
    for m in re.finditer(r"§(\d+)(?:\.(\d+))?(?:\s*(?:–|-|to)\s*§(\d+)\.(\d+))?", text):
        top, sub, top2, sub2 = m.groups()
        cited.add(top)
        if sub:
            cited.add(f"{top}.{sub}")
            if top2 == top and sub2:
                cited.update(f"{top}.{n}" for n in range(int(sub), int(sub2) + 1))
    return cited


def kind(i):
    return i.split("-")[0] if "-" in i else ("Q" if i[0] == "Q" else "Goal")


def main():
    spec = SPEC.read_text(encoding="utf-8")
    body = spec[spec.index("## 1. "):]
    universe = expand(body)
    # Goal and technical-goal IDs only count where §5 defines them.
    universe = {i for i in universe if not re.fullmatch(r"[GT][1-6]", i)} | {
        f"G{n}" for n in range(1, 7)} | {f"T{n}" for n in range(1, 6)}
    sections = set(re.findall(r"^## (\d+)\.", body, flags=re.M)) | set(re.findall(r"^### (\d+\.\d+)\b", body, flags=re.M))

    cited_by, sec_by, unknown = defaultdict(set), defaultdict(set), defaultdict(set)
    for p in PACKETS:
        name = p.parent.name
        text = p.read_text(encoding="utf-8")
        for i in expand(text):
            (cited_by if i in universe else unknown)[i].add(name[:3])
        for s in sections_cited(text):
            sec_by[s].add(name[:3])

    missing = sorted(universe - set(cited_by), key=lambda i: (kind(i), i))
    sec_missing = sorted((s for s in sections if s not in sec_by and s.split(".")[0] not in PLANNING | REFERENCE),
                         key=lambda s: [int(x) for x in s.split(".")])
    planning = sorted((s for s in sections if s.split(".")[0] in PLANNING), key=lambda s: [int(x) for x in s.split(".")])

    lines = ["# Traceability: product specification to Spec Kit packets", "",
             "Generated by `python3 tools/trace_spec.py`; do not edit by hand. Every ID in the product",
             "specification is listed with the packets (`specs/NNN-*`) whose `spec.md` cites it.", "",
             f"- Packets scanned: {len(PACKETS)}",
             f"- IDs in the specification: {len(universe)}; cited by a packet: {len(universe) - len(missing)}; not cited: {len(missing)}",
             f"- Sections in the specification: {len(sections)}; cited by a packet: {len([s for s in sections if s in sec_by])}; "
             f"planning inputs only: {len([s for s in planning if s not in sec_by])}; not cited: {len(sec_missing)}",
             f"- IDs cited by packets but not found in the specification: {len(unknown)}", ""]
    if missing:
        lines += ["## Not cited by any packet", "", ", ".join(missing), ""]
    if sec_missing:
        lines += ["## Sections not cited by any packet", "", ", ".join(f"§{s}" for s in sec_missing), ""]
    if unknown:
        lines += ["## Cited but unknown", "", ", ".join(f"{i} ({', '.join(sorted(v))})" for i, v in sorted(unknown.items())), ""]
    lines += ["## Planning inputs", "",
              "These sections describe how to build, not what to build. They feed `/speckit-plan` "
              "(technical context, data model, contracts) for the packets that need them:",
              "", ", ".join(f"§{s}" for s in planning), "",
              "§34 (open decisions) and §35 (build order) are carried by `specs/README.md` and each "
              "packet's Assumptions.", ""]
    groups = defaultdict(list)
    for i in universe:
        groups[kind(i)].append(i)
    order = ["FR", "AC", "G", "P", "TM", "M", "DL", "T", "R", "D", "DEC", "C", "DOC", "ATT", "ASG",
             "RSK", "ISS", "MTG", "A", "E", "Q", "Goal"]
    titles = {"FR": "Functional requirements", "AC": "Acceptance criteria", "A": "Attention rules",
              "E": "Edge cases", "Q": "Open decisions", "Goal": "Goals (G1–G6) and technical goals (T1–T5)"}
    for k in order:
        if k not in groups:
            continue
        lines += [f"## {titles.get(k, k + '- rules')}", "", "| ID | Packets |", "|---|---|"]
        for i in sorted(groups[k], key=lambda x: (re.sub(r"-?\d+$", "", x), int(re.search(r"(\d+)$", x)[1]))):
            lines.append(f"| {i} | {', '.join(sorted(cited_by.get(i, []))) or '**none**'} |")
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")

    problems = len(missing) + len(sec_missing) + len(unknown)
    print(f"{len(universe)} IDs, {len(missing)} not cited; {len(sections)} sections, {len(sec_missing)} not cited; "
          f"{len(unknown)} unknown")
    for label, items in (("not cited", missing), ("sections not cited", sec_missing), ("unknown", sorted(unknown))):
        if items:
            print(f"  {label}: " + ", ".join(items))
    return 1 if ("--check" in sys.argv and problems) else 0


if __name__ == "__main__":
    sys.exit(main())
